pipeline {
    agent any

    environment {
        EC2_HOST = 'ec2-13-235-75-240.ap-south-1.compute.amazonaws.com'
        DEPLOY_PATH = '/var/www/vite-react-project'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install') {
            steps {
                dir('vite-react-project') {
                    sh 'npm ci'
                }
            }
        }

        stage('Lint') {
            steps {
                dir('vite-react-project') {
                    sh 'npm run lint'
                }
            }
        }

        stage('Build') {
            steps {
                dir('vite-react-project') {
                    sh 'npm run build'
                }
            }
        }

       stage('Deploy') {
        steps {
            sh '''
            mkdir -p /var/www/vite-react-project
            rm -rf /var/www/vite-react-project/*
            cp -r vite-react-project/dist/* /var/www/vite-react-project/
            '''
        }
    }

    }

    post {
        success {
            echo 'Pipeline completed successfully.'
        }
        failure {
            echo 'Pipeline failed.'
        }
    }
}